@baseUrl = http://localhost:8000/api/v1
@userId = 019ff881-7e3b-76c9-8d0e-d46ecb1b5fc9
@adminToken = cole-o-token-de-um-administrador-aqui


### Criar usuário
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Raul Silva",
  "email": "raul@example.com",
  "password": "12345678"
}


### Login
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "raul@example.com",
  "password": "12345678"
}


### Listar usuários (somente admin)
GET {{baseUrl}}/users
Authorization: Bearer {{adminToken}}


### Buscar usuário por ID
GET {{baseUrl}}/users/{{createUser.response.body.$.id}}
Authorization: Bearer {{loginUser.response.body.$.access_token}}


### Atualizar usuário
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Raul Pontes",
  "email": "raul.pontes@example.com",
  "role": "admin"
}


### Alterar senha
PUT {{baseUrl}}/users/change_password/{{createUser.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.$.access_token}}

{
  "email": "raul@example.com",
  "new_password": "novaSenha123",
  "new_password_confirmation": "novaSenha123"
}


### Criar filme (somente admin)
# @name createMovie
POST {{baseUrl}}/movies
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Interestelar",
  "synopsis": "Exploradores atravessam um buraco de minhoca no espaço.",
  "age_rating": "10",
  "duration_minutes": 169,
  "genre": "Ficção científica",
  "trailer_url": "https://www.youtube.com/watch?v=zSWdZVtXT7E"
}


### Listar filmes (público)
GET {{baseUrl}}/movies


### Buscar filme por ID (público)
GET {{baseUrl}}/movies/{{createMovie.response.body.$.id}}


### Atualizar filme (somente admin)
PUT {{baseUrl}}/movies/{{createMovie.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "duration_minutes": 170
}


### Criar cinema (somente admin)
# @name createCinema
POST {{baseUrl}}/cinemas
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Cinema Central",
  "street": "Avenida Principal",
  "number": "100",
  "complement": "Shopping Central",
  "neighborhood": "Centro",
  "zip_code": "60000-000"
}


### Listar cinemas ativos (público)
GET {{baseUrl}}/cinemas


### Buscar cinema por ID (público)
GET {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}


### Atualizar cinema (somente admin)
PUT {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "number": "120"
}


### Criar sala (somente admin)
# @name createRoom
POST {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}/rooms
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Sala 1",
  "row_count": 10,
  "seats_per_row": 12
}


### Listar salas ativas de um cinema (público)
GET {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}/rooms


### Buscar sala por ID (público)
GET {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}/rooms/{{createRoom.response.body.$.id}}


### Atualizar sala (somente admin)
PUT {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}/rooms/{{createRoom.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "row_count": 11
}


### Criar sessão (somente admin)
# @name createSession
POST {{baseUrl}}/sessions
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "movie_id": "{{createMovie.response.body.$.id}}",
  "room_id": "{{createRoom.response.body.$.id}}",
  "starts_at": "2026-10-01T19:00:00-03:00",
  "ends_at": "2026-10-01T21:00:00-03:00",
  "price": 25.00
}


### Listar sessões ativas (público)
GET {{baseUrl}}/sessions


### Buscar sessão por ID (público)
GET {{baseUrl}}/sessions/{{createSession.response.body.$.id}}


### Atualizar sessão (somente admin)
PUT {{baseUrl}}/sessions/{{createSession.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "price": 30.00
}


### Desativar sessão (somente admin)
DELETE {{baseUrl}}/sessions/{{createSession.response.body.$.id}}
Authorization: Bearer {{adminToken}}


### Desativar sala (somente admin)
DELETE {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}/rooms/{{createRoom.response.body.$.id}}
Authorization: Bearer {{adminToken}}


### Desativar filme (somente admin)
DELETE {{baseUrl}}/movies/{{createMovie.response.body.$.id}}
Authorization: Bearer {{adminToken}}


### Desativar cinema (somente admin)
DELETE {{baseUrl}}/cinemas/{{createCinema.response.body.$.id}}
Authorization: Bearer {{adminToken}}
