@baseUrl = http://localhost:8000/api/v1
@userId = 019ff881-7e3b-76c9-8d0e-d46ecb1b5fc9
@adminToken = cole-o-token-de-um-administrador-aqui


### Criar usuário
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Raul Silva",
  "email": "raul@example.com",
  "password": "123456"
}


### Login
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "raul@example.com",
  "password": "123456"
}


### Listar usuários (somente admin)
GET {{baseUrl}}/users
Authorization: Bearer {{adminToken}}


### Buscar usuário por ID
GET {{baseUrl}}/users/{{createUser.response.body.$.id}}
Authorization: Bearer {{loginUser.response.body.$.access_token}}


### Atualizar usuário
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Raul Pontes",
  "email": "raul.pontes@example.com",
  "role": "admin"
}


### Alterar senha
PUT {{baseUrl}}/users/change_password/{{createUser.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{loginUser.response.body.$.access_token}}

{
  "email": "raul@example.com",
  "new_password": "novaSenha123",
  "new_password_confirmation": "novaSenha123"
}


### Criar filme (somente admin)
# @name createMovie
POST {{baseUrl}}/movies
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Interestelar",
  "synopsis": "Exploradores atravessam um buraco de minhoca no espaço.",
  "age_rating": "10",
  "duration_minutes": 169,
  "genre": "Ficção científica",
  "trailer_url": "https://www.youtube.com/watch?v=zSWdZVtXT7E"
}


### Listar filmes (público)
GET {{baseUrl}}/movies


### Buscar filme por ID (público)
GET {{baseUrl}}/movies/{{createMovie.response.body.$.id}}


### Atualizar filme (somente admin)
PUT {{baseUrl}}/movies/{{createMovie.response.body.$.id}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "duration_minutes": 170
}


### Excluir filme (somente admin)
DELETE {{baseUrl}}/movies/{{createMovie.response.body.$.id}}
Authorization: Bearer {{adminToken}}
