from typing import Protocol
from uuid import UUID

from app.cinemas.domain.cinema import Cinema
from app.cinemas.domain.room import Room


class CinemaRepository(Protocol):
    async def create_cinema(self, cinema: Cinema) -> Cinema: ...

    async def find_cinema_by_id(self, cinema_id: UUID) -> Cinema | None: ...

    async def find_cinema_by_name(self, name: str) -> Cinema | None: ...

    async def list_cinemas(self) -> list[Cinema]: ...

    async def update_cinema(self, cinema: Cinema) -> Cinema: ...


class RoomRepository(Protocol):
    async def create_room(self, room: Room) -> Room: ...

    async def find_room_by_id(self, cinema_id: UUID, room_id: UUID) -> Room | None: ...

    async def find_room_by_name(self, cinema_id: UUID, name: str) -> Room | None: ...

    async def list_rooms(self, cinema_id: UUID) -> list[Room]: ...

    async def update_room(self, room: Room) -> Room: ...
