from typing import Protocol
from uuid import UUID

from app.users.domain.user import User


class UserRepository(Protocol):
    async def create_user(self, user: User) -> User: ...

    async def find_by_id(self, user_id: UUID) -> User | None: ...

    async def find_by_email(self, user_email: str) -> User | None: ...

    async def update_user(self, user: User) -> User | None: ...

    async def list_user(self) -> list[User]: ...
